### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by muralive** [lukeed/is-offline#1]
node_modules/is-offline/dist/is-offline.js:6
        var fn = window[(toAdd ? 'add' : 'remove') + 'EventListener'];

When used in node. Not intended for use in node?

**Comment by lukeed** [comment]
Yeah, sorry, this is for browsers only. 

For node, you can do something simple with [`dns.resolve`](https://nodejs.org/api/dns.html#dns_dns_resolve_hostname_rrtype_callback), or pretty much any of the `dns` methods. If looking at a site like `google.com`, you'd listen for an Error response, which would indicate offline status.
